### ISSUE TITLE
Software unable to break parts

### ISSUE THREAD

**Issue by chetan-SMRI** [9swampy/DeepNestSharp#14]
When we upload dxf like this - 
![image](https://user-images.githubusercontent.com/84266613/223618038-e0d79a39-b67a-4376-b741-713f7b60d117.png)

It doesnt get me different parts as shown in photo, but in deepnest software it could differentiate btw parts and listed all parts.

**Comment by 9swampy** [comment]
Get your scissors out and chop your dxf up. The code expects and requires a single part per file. Ofc it could be handled, happy to consider a PR but make sure you don't break holes within parts logic...
