### ISSUE TITLE
DXF export error

### ISSUE THREAD

**Issue by groyk** [9swampy/DeepNestSharp#7]
Hi 9swampy

Nice project. I have tested a bit and found following issues.

- DXF export has an error when trying to open in Autocad 2021. (Opens fine in ex. NanoCAD or like).
- Sheet size on export is smaller than entered?? if entered 3000x1500, export is 2970x1470

Hoping this project will continue

I will do more testing :-)

**Comment by 9swampy** [comment]
I don't have AutoCad to verify; copy the full error message and maybe it'll be obvious but this uses a library to generate the DXF so not much I'll be able to do; more likely it's going to be on the dependency.

Sheet size I wasn't aware of this; there's some rounding [potential] errors in the code but more likely it's a bounding issue. One of the settings is space between parts(can't recall exactly which without looking in to the code); make sure that's 0 or it'll be leaving a gap between the edge of the sheet and your first part so when it exports it'll seem like your losing a margin.

**Comment by 9swampy** [comment]
Were you able to verify the issue? If no more comments I'll close off this ticket.

**Comment by FlorianSan** [comment]
Hello, 
The problem still exists! Autocad outputs this error: 
https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Press-ENTER-to-continue-and-Invalid-block-name-when-trying-to-open-a-DXF-file-in-AutoCAD.html

The causes are: 
- At least one block in the drawing has an invalid name.
- The DXF file was created as an older version, such as R10, from a third party software. If the software does not comply with the limitations of such an old file format, the files created might not be usable.

When I look at this it seems like a known problem!
https://github.com/ixmilia/dxf#autocad

![error](https://user-images.githubusercontent.com/17226527/228911760-73fb7383-6a6f-4e23-ba11-aaa60ebe05c2.jpg)
