### ISSUE TITLE
X and Y coordinates

### ISSUE THREAD

**Issue by dgeoffre** [9swampy/DeepNestSharp#9]
Hi !
Thanks for the nesting code, works perfectly
I just struggle to understand what the X and Y coordinates given in the .dnsp file are. Are they the coordinates of a special point for each part ? It seems to be changing wether the part has been rotated or not during the nesting.
Thanks again

**Comment by 9swampy** [comment]
They're just the offset of the part from the origin on the sheet.

<img src="https://github.com/9swampy/DeepNestSharp/raw/master/imgs/SheetPlacementEditor.png"/>

On the Sheet Placement Editor you can edit the offsets or Shift+Click on parts to drag/drop in the Preview. FYI dragging is a little out of sync so multiple small moves work better than one large move. . . and atm you can only move around parts already present; todo => moving from one sheet to another, adding & removing additional parts etc.

**Comment by dgeoffre** [comment]
okay, thanks for the answer, I managed to use the coordinates correctly ! 
Unfortunately, I'm struggling to nest some parts, the Pmap phase takes a lot of time... (like 15 min for each placement)
What is the purpose of the Pmap phase ? I'm nesting parts like these :
![Capture baj](https://user-images.githubusercontent.com/103993996/168020426-ab1616ae-aee8-40f5-a3b5-025747b51ebb.JPG)

Do you think that the small notch in the part can be a problem for DeepNest ?
 
Thanks !

**Comment by 9swampy** [comment]
No the notch shouldn't be an issue. The pair-map is the core of the NoFitPolygon algorithm that generates the nest and it can take a while, but 15 mins a placement doesn't sound right. How many parts are you trying to nest?

**Comment by dgeoffre** [comment]
I'm trying to nest 70 parts like these, maybe the problem comes from the precision of my dxfs, my dxfs are 17Ko for each part.
It seems that reducing the number of points in the dxfs accelerates the process

**Comment by 9swampy** [comment]
Curve Tolerance and Clip By Hull would have a similar effect sacrificing the tightness of the nest without losing precision on the individual parts ultimately output. As your original question is answered, if you don't mind could you close this issue?
